version: '3.7' # specify docker-compose version

services:
  # Create backend container
   backend:
    build: ./server
    container_name: backend_docker
    image: registry.thedigitalacademy.co.za/fs/geeks
    ports:
      - '3000:3000'
   frontend:
    build: ./client
    container_name: frontend_docker
    image: registry.thedigitalacademy.co.za/fs/geeks
    ports:
      - '4545:4545'